def get_raw_data():
    return [{'date': '2019-06-01', 'value': {
        'hidden_photo': {'anger': 0.0, 'contempt': 0.0, 'disgust': 0.0,
                         'fear': 0.0, 'happiness': 0.0, 'neutral': 0.999,
                         'sadness': 0.001, 'surprise': 0.0}, 'feeling': 2,
        'unhidden_photo': {'anger': 0.0, 'contempt': 0.0, 'disgust': 0.0,
                           'fear': 0.0, 'happiness': 0.0, 'neutral': 0.999,
                           'sadness': 0.001, 'surprise': 0.0}}},
            {'date': '2019-05-31', 'value': {
                'hidden_photo': {'anger': 0.2, 'contempt': 0.0, 'disgust': 0.0,
                                 'fear': 0.3, 'happiness': 0.0, 'neutral': 0.0,
                                 'sadness': 0.5, 'surprise': 0.0},
                'feeling': 1,
                'unhidden_photo': {'anger': 0.0, 'contempt': 0.0,
                                   'disgust': 0.0,
                                   'fear': 0.3, 'happiness': 0.5,
                                   'neutral': 0.0,
                                   'sadness': 0.2, 'surprise': 0.0}}},
            {'date': '2019-05-29', 'value': {
                'hidden_photo': {'anger': 0.0, 'contempt': 0.0, 'disgust': 0.0,
                                 'fear': 0.1, 'happiness': 0.0, 'neutral': 0.6,
                                 'sadness': 0.3, 'surprise': 0.0},
                'feeling': 2,
                'unhidden_photo': {'anger': 0.0, 'contempt': 0.0,
                                   'disgust': 0.0,
                                   'fear': 0.3, 'happiness': 0.5,
                                   'neutral': 0.0,
                                   'sadness': 0.2, 'surprise': 0.0}}},
            {'date': '2019-05-28', 'value': {
                'hidden_photo': {'anger': 0.0, 'contempt': 0.0, 'disgust': 0.0,
                                 'fear': 0.1, 'happiness': 0.5, 'neutral': 0.4,
                                 'sadness': 0.1, 'surprise': 0.0},
                'feeling': 4,
                'unhidden_photo': {'anger': 0.0, 'contempt': 0.0,
                                   'disgust': 0.0,
                                   'fear': 0.3, 'happiness': 0.5,
                                   'neutral': 0.0,
                                   'sadness': 0.2, 'surprise': 0.0}}},
            {'date': '2019-05-27', 'value': {
                'hidden_photo': {'anger': 0.0, 'contempt': 0.0, 'disgust': 0.0,
                                 'fear': 0.0, 'happiness': 0.0, 'neutral': 0.8,
                                 'sadness': 0.2, 'surprise': 0.0},
                'feeling': 1,
                'unhidden_photo': {'anger': 0.0, 'contempt': 0.0,
                                   'disgust': 0.0,
                                   'fear': 0.3, 'happiness': 0.5,
                                   'neutral': 0.0,
                                   'sadness': 0.2, 'surprise': 0.0}}},
            {'date': '2019-05-26', 'value': {
                'hidden_photo': {'anger': 0.0, 'contempt': 0.0, 'disgust': 0.0,
                                 'fear': 0.2, 'happiness': 0.2, 'neutral': 0.3,
                                 'sadness': 0.3, 'surprise': 0.0},
                'feeling': 2,
                'unhidden_photo': {'anger': 0.0, 'contempt': 0.0,
                                   'disgust': 0.0,
                                   'fear': 0.3, 'happiness': 0.5,
                                   'neutral': 0.0,
                                   'sadness': 0.2, 'surprise': 0.0}}},
            {'date': '2019-05-15', 'value': {
                'hidden_photo': {'anger': 0.0, 'contempt': 0.0, 'disgust': 0.0,
                                 'fear': 0.0, 'happiness': 0.0, 'neutral': 0.0,
                                 'sadness': 1.0, 'surprise': 0.0},
                'feeling': 3,
                'unhidden_photo': {'anger': 0.0, 'contempt': 0.0,
                                   'disgust': 0.0,
                                   'fear': 0.3, 'happiness': 0.5,
                                   'neutral': 0.0,
                                   'sadness': 0.2, 'surprise': 0.0}}}]

